spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/backend_morphism
spring.datasource.username=bm_user
spring.datasource.password=Bm@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect